FROM public.ecr.aws/lambda/python:3.9

# 1. Instalar uv
RUN pip install uv

# 2. Copiar archivos de dependencias
COPY pyproject.toml uv.lock ./

# 3. Exportar las dependencias e instalarlas en el sistema
RUN uv export --format requirements-txt --no-hashes --no-emit-workspace > requirements.txt && \
    uv pip install --system -r requirements.txt

# 4. Copiar código, modelos y el handler
COPY credit_scoring ./credit_scoring
COPY models ./models
COPY lambda_function.py .

# 5. Handler de la función Lambda
CMD ["lambda_function.lambda_handler"]